In [98]:
import torch ## import pytorch
import numpy as np ## import of numpy
#from torch.utils.tensorboard import SummaryWriter

In [99]:
## Vector 1D:
## Matrix 2D:
## Tensor ND: (1-N)
## A pytorch tensor (random)
vector = np.array([[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]])
print(vector.shape)


print(ten_n.shape)
ten = torch.tensor([1., 2., 3.]) ## 1D tensor
print(ten.shape)
print(ten.type())
a = torch.FloatTensor([[[1, 2, 3]]])
print(a.shape)


(2, 2, 3)
(3,)
torch.Size([3])
torch.FloatTensor
torch.Size([1, 1, 3])


In [100]:
## clear content of a tensor (without altering the tensor) (Functional, makes a copy
## of the tensor)
# b = torch.zeros_like(a) ## 
# print(a)
# print(b)
# print(a)
# print()
## clear content of a tensor (alter the tensor)
a.zero_()
print(a)
print(a)

tensor([[[0., 0., 0.]]])
tensor([[[0., 0., 0.]]])


In [101]:
## we make a numpy array
a_numpy = np.random.normal(loc=0, scale=1.0, size=(3,2)) ## create a random uniform distrib (mean=0, std=1.0 size=(3,2))

## convert it into pytorch tensor
a_tensor = torch.tensor(a_numpy, dtype=torch.float)
a_tensor

tensor([[-0.2350,  0.4726],
        [ 1.1150, -1.0532],
        [ 1.0129, -2.2621]])

In [102]:
## tensor operations
a = torch.tensor([1., 2., -3.])
print(a.sum())
print(a)
print(a.mean())
print(a.mode())
print(a.median())
print(a.abs())
#print(a.)

tensor(0.)
tensor([ 1.,  2., -3.])
tensor(0.)
torch.return_types.mode(
values=tensor(-3.),
indices=tensor(2))
tensor(1.)
tensor([1., 2., 3.])


In [103]:
## GPU tensors
print(a) ## this is a cpu tensor when you make it
print(a.device) ## to see what the device that tensor assigned to
print(a.to('cuda')) ## assign to the GPU
print(a.to('cuda').device)

tensor([ 1.,  2., -3.])
cpu
tensor([ 1.,  2., -3.], device='cuda:0')
cuda:0


In [104]:
## tensor gradients
v1 = torch.tensor([1.0, 2.0]) ## does not required gradient computation
v2 = torch.tensor([3.1, 1.0], requires_grad=True) ## require gradient computation

## operate on the tensors
v_sum = v1 + v2 ## computation graph step-1
v_res = (v_sum*2).sum() ## computation graph step-2
#print(v_sum)
#print(v_res)

## user made tensors are leafs in  a graph
## but intermediate operations are not
print(v1.is_leaf)
print(v_sum.is_leaf)

'''
with torch.no_grad():
    ## execute you model
'''
## are gradients required
#print(v1.requires_grad)
#print(v2.grad)

True
False


'\nwith torch.no_grad():\n    ## execute you model\n'

In [105]:
## NN blocks
import torch.nn as nn
linear_layer = nn.Linear(3, 5, bias=True) ## y = x(A)^T + b
## A weight matrix and b = biases
inp = torch.tensor([1, 2, 3], dtype=torch.float)
linear_layer(inp)

tensor([-2.4022, -1.0323, -3.6486, -1.0001, -1.1885], grad_fn=<AddBackward0>)

In [106]:
## layer parameter
print(linear_layer.parameters()) ## return a generator that yields the layer parameter (A, b); A: 3x5 b: 3
for i in linear_layer.parameters():
    print(i)

<generator object Module.parameters at 0x7f513cccfc80>
Parameter containing:
tensor([[-0.2714, -0.3254, -0.5139],
        [ 0.2984, -0.1070, -0.4282],
        [-0.5565, -0.5276, -0.5051],
        [ 0.4509, -0.4152, -0.0419],
        [-0.4561, -0.0479, -0.2294]], requires_grad=True)
Parameter containing:
tensor([ 0.0616,  0.1677, -0.5217, -0.4948,  0.0515], requires_grad=True)


In [115]:
## layer parameter
print(linear_layer.state_dict()) ## parameters and biases as a dictionary

OrderedDict([('weight', tensor([[-0.2714, -0.3254, -0.5139],
        [ 0.2984, -0.1070, -0.4282],
        [-0.5565, -0.5276, -0.5051],
        [ 0.4509, -0.4152, -0.0419],
        [-0.4561, -0.0479, -0.2294]])), ('bias', tensor([ 0.0616,  0.1677, -0.5217, -0.4948,  0.0515]))])


In [116]:
## A simple ANN model
model = nn.Sequential( ### stack layers to make a neural network graph
    nn.Linear(2,5), ## first layer
    nn.ReLU(), ## first activation function
    nn.Linear(5,20),
    nn.ReLU(),
    nn.Linear(20,10),
    nn.ReLU(),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1)
)
model

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): ReLU()
  (6): Dropout(p=0.3, inplace=False)
  (7): Softmax(dim=1)
)

In [118]:
inp = torch.FloatTensor([[1,2]]) ## dummy inputs
model(inp) ## call forward on the network

tensor([[0.0851, 0.0851, 0.0851, 0.0915, 0.1859, 0.0851, 0.0851, 0.1269, 0.0851,
         0.0851]], grad_fn=<SoftmaxBackward>)

In [110]:
## model construction by subclassing
class Model(nn.Module):
    def __init__(self, input_shape, output_shape, drop=0.3):
        super(Model, self).__init__()
        self.model = nn.Sequential(
                        nn.Linear(2,5),
                        nn.ReLU(),
                        nn.Linear(5,20),
                        nn.ReLU(),
                        nn.Linear(20,1),
                        #nn.ReLU(),
                        #nn.Dropout(p=0.3),
                        #nn.Softmax(dim=1)
                        )
    ## forward pass of the NN
    def forward(self, x):
        return self.model(x)


In [111]:
## construct the model
net = Model(2, 3)
inp = torch.FloatTensor([[2, 3]])
out = net(inp)
print(net)
print(out)

Model(
  (model): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=1, bias=True)
  )
)
tensor([[-0.0265]], grad_fn=<AddmmBackward>)


In [112]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001)

In [113]:
## make some random data
inp_batch = torch.normal(0, 1, (1000, 2))
inp_batch.size()
tgt_batch = torch.normal(0, 1, (1000, 1))

In [114]:
writer = SummaryWriter()
for e in range(100):
    epoch_loss = list()
    for i in range(0, inp_batch.shape[0], 10):
        inp = inp_batch[i:i+10]
        tgt = tgt_batch[i:i+10]
        out = net(inp)
        #print(out.shape)
        optimizer.zero_grad()
        loss = nn.MSELoss()(out, tgt)
        loss.backward()
        optimizer.step()
        epoch_loss.append(loss.item())
        writer.add_scalar("error", loss.item())
    print(np.array(np.mean(epoch_loss)))
writer.close()

    

NameError: name 'SummaryWriter' is not defined